import { ProcessedTestResult, ProcessedCoverageResult } from "./interfaces"

export function formatResults(
  results: ProcessedTestResult[],
  coverageResults: ProcessedCoverageResult[],
  showCoverage: boolean,
): string {
  let output = `# ${process.env.pr_comment_title || "🧪 OPA Rego Policy Test Results"}\n\n`;

  if (showCoverage) {
    output += "| File | Status | Passed | Total | Coverage | Details |\n";
    output += "|------|--------|--------|-------|----------|----------|\n";
  } else {
    output += "| File | Status | Passed | Total | Details |\n";
    output += "|------|--------|--------|-------|----------|\n";
  }

  for (const result of results) {
    let statusEmoji, statusText;
    switch (result.status) {
      case "PASS":
        statusEmoji = "✅";
        statusText = `${statusEmoji} PASS`;
        break;
      case "FAIL":
        statusEmoji = "❌";
        statusText = `${statusEmoji} FAIL`;
        break;
      case "NO TESTS":
        statusEmoji = "⚠️";
        statusText = `${statusEmoji} NO TESTS`;
        break;
    }

    const testFileName = result.file;

    let coverageInfo;
    // Find the corresponding coverage test information for the test result we're on
    if (showCoverage) {
      coverageInfo = coverageResults.find((cr) => {
        const lastSlashIndex = cr.file.lastIndexOf("/");
        const dotRegoIndex = cr.file.lastIndexOf(".rego");

        // Check if the file paths are valid
        if (lastSlashIndex === -1 || dotRegoIndex === -1) return false;

        // Extract the base file name without extension from the coverage report
        const fileNameWithoutExtension = cr.file.slice(
          lastSlashIndex + 1,
          dotRegoIndex,
        );

        // Match the test file with its corresponding implementation file in the coverage results
        // Test files typically have names like 'abc_test.rego', while coverage is reported for 'abc.rego' because the test file is testing the implementation file, and the coverage is on how much the implementation file is covered.
        // We want to associate the coverage data from 'abc.rego' with the test results from 'abc_test.rego'
        return (
          testFileName.includes(fileNameWithoutExtension) &&
          !cr.file.includes(testFileName)
        );
      });
    }

    const details =
      result.status === "NO TESTS"
        ? "No test file found"
        : result.details.join("<br>");

    const detailsColumn = `<details><summary>Show Details</summary>${details}</details>`;

    let row = `| ${testFileName} | ${statusText} | ${result.passed} | ${result.total} `;

    if (showCoverage) {
      let coverageText = "N/A";
      let uncoveredLinesDetails = "";
      if (coverageInfo) {
        coverageText = `${coverageInfo.coverage.toFixed(2)}%`;
        if (
          coverageInfo.notCoveredLines &&
          coverageInfo.notCoveredLines !== "N/A"
        ) {
          uncoveredLinesDetails = `<details><summary>Uncovered Lines</summary>${coverageInfo.notCoveredLines}</details>`;
        }
      }
      row += `| ${coverageText} ${uncoveredLinesDetails} `;
    }

    row += `| ${detailsColumn} |\n`;
    output += row;
  }

  if (process.env.indicate_source_message === "true") {
    output +=
      "\n\n<small>Report generated by [🧪 GitHub Actions for OPA Rego Test](https://github.com/masterpointio/github-action-opa-rego-test)</small>";
  }

  return output;
}
