import { ProcessedTestResult, ProcessedCoverageResult } from "./interfaces";

/**
 * Formats the test results and coverage results into a Markdown table for GitHub comments.
 * @param results - The processed test results.
 * @param coverageResults - The processed coverage results.
 * @param showCoverage - Whether to include coverage information in the output.
 * @returns A string containing the formatted Markdown table.
 */
export function formatResults(
  results: ProcessedTestResult[],
  coverageResults: ProcessedCoverageResult[],
  showCoverage: boolean,
): string {
  let output = `# ${process.env.pr_comment_title || "🧪 OPA Rego Policy Test Results"}\n\n`;

  // Build header row
  let header = "| File | Status | Passed | Total |";
  let separator = "|------|--------|--------|-------|";

  if (showCoverage) {
    header += " Coverage |";
    separator += "----------|";
  }
  header += " Details |\n";
  separator += "----------|\n";
  output += header;
  output += separator;

  for (const result of results) {
    let statusEmoji, statusText;
    switch (result.status) {
      case "PASS":
        statusEmoji = "✅";
        statusText = `${statusEmoji} PASS`;
        break;
      case "FAIL":
        statusEmoji = "❌";
        statusText = `${statusEmoji} FAIL`;
        break;
      case "NO TESTS":
        statusEmoji = "⚠️";
        statusText = `${statusEmoji} NO TESTS`;
        break;
    }

    const testFileName = result.file;
    const details =
      result.status === "NO TESTS"
        ? "No test file found"
        : result.details.join("<br>");
    const detailsColumn = `<details><summary>Show Details</summary>${details}</details>`;

    let row = `| ${testFileName} | ${statusText} | ${result.passed} | ${result.total} |`;

    if (showCoverage) {
      const coverageInfo = coverageResults.find((cr) => {
        const lastSlashIndex = cr.file.lastIndexOf("/");
        const dotRegoIndex = cr.file.lastIndexOf(".rego");

        if (lastSlashIndex === -1 || dotRegoIndex === -1) return false;

        const fileNameWithoutExtension = cr.file.slice(
          lastSlashIndex + 1,
          dotRegoIndex,
        );
        return (
          testFileName.includes(fileNameWithoutExtension) &&
          !cr.file.includes(testFileName)
        );
      });

      let coverageText = "N/A";
      let uncoveredLinesDetails = "";
      if (coverageInfo) {
        try {
          coverageText = `${coverageInfo.coverage.toFixed(2)}%`;
          if (
            coverageInfo.notCoveredLines &&
            coverageInfo.notCoveredLines !== "N/A"
          ) {
            uncoveredLinesDetails = ` <details><summary>Uncovered Lines</summary>${coverageInfo.notCoveredLines}</details>`;
          }
          coverageText += uncoveredLinesDetails; // Combine text and details
        } catch (error) {
          console.error("Error processing coverage information:", error);
          console.log("Coverage Info:", coverageInfo);
          // Keep coverageText as "N/A" or set to an error message if preferred
        }
      }
      row += ` ${coverageText} |`;
    }

    row += ` ${detailsColumn} |\n`;
    output += row;
  }

  if (process.env.indicate_source_message === "true") {
    output +=
      "\n\n<small>Report generated by [🧪 GitHub Actions for OPA Rego Test](https://github.com/masterpointio/github-action-opa-rego-test)</small>";
  }

  return output;
}
