name: Tests

on: pull_request

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  test-typescript:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test

  test-action-on-itself:
    name: Test the GitHub Action on itself
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          path: ./examples
          report_untested_files: true
          pr_comment_title: "Below is the Action testing on itself with this PR's source code against the `/examples` directory. Confirm it is as expected."
