# Workflow to perform a clean installation, cache/restore them, build the source, and run the tests to confirm it all works as expected.

name: Test

on:
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
